const { redact } = require("./security.cjs");
const escape = (s) =>
  redact(s).replace(
    /[&<>"']/g,
    (c) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[
        c
      ],
  );
function report(record) {
  const security = Array.isArray(record.findings),
    status = record.status || "not measured";
  const evidence = security ? record : record.securityEvidence || {};
  const row = (a, b) =>
    `<div class="row"><span>${escape(a)}</span><strong>${escape(b ?? "Not measured")}</strong></div>`;
  const checks = security ? record.scanners : record.checks || [];
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'"><title>TokenPilot / ${escape(status)}</title><style>body{margin:0;background:#f4f3ed;color:#202b28;font:16px/1.65 system-ui,sans-serif}main{max-width:960px;margin:auto;padding:48px 24px}header{border-top:8px solid #25654c;padding-top:24px}h1{font:48px/1.1 Georgia,serif}h2{margin-top:40px}small,.muted{color:#59665f}.row{display:flex;justify-content:space-between;gap:24px;border-bottom:1px solid #d8ddd5;padding:16px 0;overflow-wrap:anywhere}article{background:#fff;border:1px solid #d8ddd5;padding:24px;margin:16px 0}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:13px/1.6 monospace;background:#eeeee7;padding:16px}strong{font-variant-numeric:tabular-nums}code{overflow-wrap:anywhere}</style></head><body><main><header><small>TOKENPILOT / LOCAL EVIDENCE REPORT</small><h1>${escape(status.replaceAll("-", " ").replaceAll("_", " "))}</h1><p>${escape(security ? "Repository security review" : record.task)}</p><p class="muted">${escape(record.root)}<br>${escape(new Date(record.started).toISOString())}</p></header>
 ${row("Run", record.id)}${row("Source snapshot", evidence.snapshot?.hash)}${row("Model tokens", security ? 0 : record.usage ? require("./policy.cjs").usageTokens(record.usage) : null)}${row("Findings", security ? record.findings.length : null)}${row("Candidate groups", evidence.groups?.length)}
 <h2>Verification gates</h2>${record.ci ? row("CI policy", record.ci.status) + `<p>${escape(record.ci.reason)}</p>` : ""}${row("Security gate", evidence.gateStatus || evidence.status || "Not evaluated")}${checks.map((c) => row(c.tool || c.id, c.status)).join("")}${row("Behavioral reproduction", evidence.proof?.status || "Not evaluated")}${row("Independent Challenger", "Not implemented")}
 <p class="muted">A static finding is not a reproduced exploit. Scanner clearance is not behavioral verification. Missing checks are never shown as passed. Grouping uses rule and file, not a claim that a shared root cause has been proven.</p>
 ${evidence.comparison ? `<h2>Before / after</h2>${row("Groups cleared", evidence.comparison.cleared.length)}${row("Remaining findings", evidence.comparison.remaining.length)}${row("New findings", evidence.comparison.introduced.length)}` : ""}
 ${(evidence.groups || []).map((g) => `<article><h3>${escape(g.rule)}</h3><code>${escape(g.file)}</code><p>${escape(g.findings[0]?.message)}</p>${row("Locations", g.findings.map((f) => f.line).join(", "))}${row("Evidence", "Static scanner output")}</article>`).join("")}
 ${evidence.proof?.before ? `<h2>Frozen behavioral probe</h2>${row("Original snapshot", evidence.proof.before.status)}${row("Changed snapshot", evidence.proof.after.status)}<pre>${escape(evidence.proof.after.output || evidence.proof.after.reason)}</pre>` : ""}
 ${evidence.evasion?.length ? `<h2>Patterns requiring review</h2><pre>${escape(JSON.stringify(evidence.evasion, null, 2))}</pre>` : ""}
 ${record.changes?.diff ? `<h2>Patch</h2><pre>${escape(record.changes.diff)}</pre>` : ""}
 ${record.result ? `<h2>Outcome</h2><p>${escape(record.result)}</p>` : ""}
 <h2>Scope and limitations</h2><p>Local scans use the bundled focused Semgrep rules and Gitleaks defaults. This is not a comprehensive security audit. Generated directories and files over 4 MB are outside the source scan. Pattern redaction cannot recognize every possible secret; review this report before sharing.</p><p>${escape(record.error || record.accounting || "No AI was used for scanning or grouping. No token savings estimate is implied by these counts.")}</p><small>Generated by TokenPilot. Offline HTML, no scripts, external assets or tracking.</small></main></body></html>`;
}
module.exports = { report, escape };
